version: "3.8"

services:
  ycast:
    image: ghcr.io/tobiaspankner/ycast-cache:latest
    container_name: ycast
    ports:
      - "80:80"
    volumes:
      - ycast-data:/root/.ycast
    environment:
      - YCAST_DEBUG=false
    restart: unless-stopped

volumes:
  ycast-data:
